spring:
  datasource:
    url: ${SPRING_DATASOURCE_BANK_URL}
    username: ${SPRING_DATASOURCE_BANK_USERNAME}
    password: ${SPRING_DATASOURCE_BANK_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate

auth:
  token:
    jwt-secret: PE+01rgtPbv1Xr4JxgTwcB2oB+m+4NZVD+SO+WBiudE=
    expiration: 36000000

jasypt:
  encryptor:
    secret: mySecretKeys
    algorithm: PBEWithMD5AndDES
    salt: fixedsalt

server:
  port: 8088